language: go
sudo: required

go:
  - "1.12"

services:
  - docker

before_install:
  - docker pull vicanso/etcd 
  - docker run -p 2379:2379 -d vicanso/etcd etcd --listen-client-urls 'http://0.0.0.0:2379' --advertise-client-urls 'http://0.0.0.0:2379'

script:
  - make test
  - docker build -t varnish-agent .


after_success:
  - export VERSION=1.0.0
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag varnish-agent $DOCKER_USERNAME/varnish-agent:$VERSION
  - docker tag varnish-agent $DOCKER_USERNAME/varnish-agent:latest
  - docker push $DOCKER_USERNAME/varnish-agent:$VERSION
  - docker push $DOCKER_USERNAME/varnish-agent:latest
  - docker images